---
apiVersion: v1
kind: Pod
metadata:
  name: cats
  namespace: cats
  labels:
    run: cats
spec:
  #replicas: 2
  containers:
  - image: 331023838533.dkr.ecr.us-east-1.amazonaws.com/cats-ecr:latest
    name: cats
    ports:
    - containerPort: 80
      name: http-web
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  