apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cats
  labels:
    app.kubernetes.io/name: cats
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cats
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cats
    spec:
      containers:
      - name: cats
        image: 331023838533.dkr.ecr.us-east-1.amazonaws.com/cats-ecr:latest
        ports:
        - containerPort: 80
        
        